### ISSUE TITLE
[BUG] @item.level not working in the "Other formula" field of a spell when Auto Roll is set to "True"

### ISSUE THREAD

**Issue by DarKDinDoN** [ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E#30]
Hello,

FVTT 0.9.245
5e 1.5.7
MRE 3.2.6

Assuming a spell with the following configuration:
- Other formula set to `@item.level`
- Auto Roll: True

![image](https://user-images.githubusercontent.com/1687854/151979009-a2643e9e-eb87-42b0-8a83-06eede586794.png)

If the spell was upcast, then `@item.level` is parsed to the normal spell level not the upcast level.

Example:
- Level 1 spell cast at level 1 will print 1 ✅ 
- Level 1 spell upcast at level 3 will print 1 as well 🟥 (should be 3)

All other conbinations seem OK. It only fails when the spell is upcast and the "other formula" field is set to AutoRoll.

**Comment by akrigline** [comment]
`Item5e.rollFormula` takes in an argument which is an object that can contain `spellLevel`.

This file needs two things to fix this:
https://github.com/ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E/blob/master/scripts/patches/item-base-roll-patch.mjs

1. the `spellLevel` const needs to be moved out of the `hasDamage` if
2. the `rollFormula` call needs the following argument: `{spellLevel}`

If you can test this and open a PR, that would rock. Otherwise I'll be able to get to it in the next few days.

**Comment by DarKDinDoN** [comment]
@akrigline sure thing. Here it is: https://github.com/ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E/pull/31
